- name: apt-get update
  sudo: yes
  apt: update_cache=yes

- name: install packages
  sudo: yes
  apt: pkg={{ item }}
  with_items:
    - build-essential
    - git
    - vim
    - curl
    - htop
    - screen
    - python-dev
    - python-pycurl # for ansible
    - python-pip # for ansible
    - python-passlib # for ansible
