---
galaxy_info:
  author: George Miroshnykov
  description: set limits via /etc/security/limits.d and /etc/sysctl.d
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
